"""empty message

Revision ID: 536b519b05b5
Revises: d2f9362cec4d
Create Date: 2020-05-05 17:27:25.395054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536b519b05b5'
down_revision = 'd2f9362cec4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('street', sa.Integer(), nullable=True),
    sa.Column('volunteer', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
