"""empty message

Revision ID: d2f9362cec4d
Revises: 5a572eac22c0
Create Date: 2020-05-05 16:55:23.220758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f9362cec4d'
down_revision = '5a572eac22c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streets_districts',
    sa.Column('streets_id', sa.Integer(), nullable=True),
    sa.Column('districts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['districts_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['streets_id'], ['streets.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streets_districts')
    op.drop_table('districts')
    # ### end Alembic commands ###
